export const heroStats = [
  { label: 'Students enrolled', value: '1.8K+' },
  { label: 'Artworks created', value: '4.5K+' },
  { label: 'Workshops held', value: '42' },
];

export const courses = [
  {
    id: 'course-elementary',
    title: 'Elementary',
    slug: 'elementary',
    description: 'Foundational drawing certification track for early learners building core observation and sketching skills.',
    duration: 'Certification track',
    price: 8000,
    level: 'Elementary',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-intermediate',
    title: 'Intermediate',
    slug: 'intermediate',
    description: 'Intermediate drawing curriculum focused on stronger composition, shading, and portfolio development.',
    duration: 'Certification track',
    price: 9000,
    level: 'Intermediate',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-regular-drawing-8-turns',
    title: 'Regular Drawing Classes (8 turns)',
    slug: 'regular-drawing-8-turns',
    description: 'Weekly regular drawing classes for steady practice, observation work, and sketchbook discipline.',
    duration: '8 turns',
    price: 800,
    level: 'Beginner',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e35ca?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-black-white-pencil-shading',
    title: 'Black and White Pencil Shading - 4 Portraits with Basics',
    slug: 'black-white-pencil-shading',
    description: 'Focused portrait shading program covering tonal control, portrait structure, and four guided finished studies.',
    duration: '4 portraits',
    price: 4000,
    level: 'Beginner',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1579762715118-a6f1d789a1e4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-colour-pencil-shading',
    title: 'Colour Pencil Shading - 4 Portraits with Basics',
    slug: 'colour-pencil-shading',
    description: 'Portrait color blending course built around color pencil layering, skin tones, and four completed portraits.',
    duration: '4 portraits',
    price: 5000,
    level: 'Intermediate',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-handwriting-english',
    title: 'Handwriting Improvement (English)',
    slug: 'handwriting-improvement-english',
    description: 'Structured handwriting improvement program for English writing clarity, speed, and presentation.',
    duration: 'Skill program',
    price: 4000,
    level: 'All levels',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-handwriting-teacher-training',
    title: 'Handwriting Teacher Training with Material',
    slug: 'handwriting-teacher-training',
    description: 'Teacher training course for handwriting instructors with guided material support.',
    duration: 'Teacher training',
    price: 6000,
    level: 'Advanced',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-handwriting-hindi-marathi',
    title: 'Handwriting Improvement (Hindi or Marathi)',
    slug: 'handwriting-improvement-hindi-marathi',
    description: 'Regional language handwriting program for improved neatness, rhythm, and confidence.',
    duration: 'Skill program',
    price: 3000,
    level: 'All levels',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1471107340929-a87cd0f5b5f3?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-drawing-teacher-training',
    title: 'Drawing Teacher Training with Elementary and Intermediate',
    slug: 'drawing-teacher-training',
    description: 'Comprehensive teacher training program combining elementary and intermediate drawing methods.',
    duration: 'Teacher training',
    price: 25000,
    level: 'Advanced',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1456086272160-b28b0645b729?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-calligraphy-pens-basics',
    title: 'Calligraphy with Pens (Basics)',
    slug: 'calligraphy-pens-basics',
    description: 'Introductory pen calligraphy program covering strokes, spacing, and graceful letter structure.',
    duration: 'Skill program',
    price: 1500,
    level: 'Beginner',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1455390582262-044cdead277a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-calligraphy-brushes-advance',
    title: 'Calligraphy with Painting Brushes and Brush Pens',
    slug: 'calligraphy-brushes-advance',
    description: 'Advanced brush and brush pen calligraphy training with faux calligraphy and expressive lettering.',
    duration: 'Advanced skill program',
    price: 3000,
    level: 'Advanced',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-calligraphy-teacher-training',
    title: 'Calligraphy Teacher Training (Pen, Paint Brush, Brush Pen and 3D)',
    slug: 'calligraphy-teacher-training',
    description: 'Teacher training track for multiple calligraphy tools including pen, paint brush, brush pen, and 3D lettering.',
    duration: 'Teacher training',
    price: 6000,
    level: 'Advanced',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1500462918059-b1a0cb512f1d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-madhubani-basic',
    title: 'Madhubani Painting on Handmade Paper with Basic',
    slug: 'madhubani-painting-basic',
    description: 'Traditional Madhubani introduction on handmade paper with guided motifs, borders, and basic techniques.',
    duration: 'A4 project course',
    price: 1500,
    level: 'Beginner',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-canvas-painting',
    title: 'Canvas Painting with Oil or Acrylic Colours',
    slug: 'canvas-painting',
    description: 'Canvas painting classes in oil or acrylic. Final pricing depends on canvas size and project scope.',
    duration: 'Project based',
    price: 0,
    priceLabel: 'Depends on canvas size',
    level: 'All levels',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1499781350541-7783f6c6a0c8?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-fabric-painting-basic',
    title: 'Fabric Painting with Basic',
    slug: 'fabric-painting-basic',
    description: 'Practical fabric painting course introducing color application, motifs, and wearable surface design.',
    duration: 'Skill program',
    price: 2500,
    level: 'Beginner',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1528459801416-a9e53bbf4e17?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-glass-painting',
    title: 'Glass Painting',
    slug: 'glass-painting',
    description: 'Decorative glass painting classes with pricing based on selected surface size and design complexity.',
    duration: 'Project based',
    price: 0,
    priceLabel: 'Depends on size',
    level: 'All levels',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1509281373149-e957c6296406?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-lippan-art',
    title: 'Lippan Art',
    slug: 'lippan-art',
    description: 'Mirror and relief Lippan art workshops with pricing based on artwork size and finish.',
    duration: 'Project based',
    price: 0,
    priceLabel: 'Depends on size',
    level: 'All levels',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-coffee-painting',
    title: 'Coffee Painting on Handmade Paper',
    slug: 'coffee-painting',
    description: 'Creative monochrome coffee painting class on handmade paper for textured, tonal artwork.',
    duration: 'Project course',
    price: 1200,
    level: 'Beginner',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1494888374810-c88f8d29f26f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'course-mural-painting',
    title: 'Mural Painting',
    slug: 'mural-painting',
    description: 'Custom mural painting training and project guidance with pricing based on artwork size and surface.',
    duration: 'Project based',
    price: 0,
    priceLabel: 'Depends on size',
    level: 'Advanced',
    format: 'Offline',
    image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=800&q=80',
  },
];

export const galleryItems = [
  {
    id: 'gallery-portrait-poise',
    category: 'Sketch',
    title: 'Portrait Poise',
    artist: 'Ava Collins',
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=900&q=90',
    medium: 'Graphite on textured paper',
    mentor: 'Rhea Sharma',
    details: 'A tonal portrait study focused on soft transitions and anatomical structure.',
  },
  {
    id: 'gallery-sunset-bloom',
    category: 'Watercolor',
    title: 'Sunset Bloom',
    artist: 'Ethan Park',
    image: 'https://images.unsplash.com/photo-1500534314209-a25ddb2bd429?auto=format&fit=crop&w=900&q=90',
    medium: 'Watercolor and ink',
    mentor: 'Mira Joshi',
    details: 'A floral composition designed to practice layering, bloom effects, and warm harmony.',
  },
  {
    id: 'gallery-golden-dream',
    category: 'Oil',
    title: 'Golden Dream',
    artist: 'Maya Reed',
    image: 'https://images.unsplash.com/photo-1511765224389-37f0e77cf0eb?auto=format&fit=crop&w=900&q=90',
    medium: 'Oil on canvas',
    mentor: 'Liam Dsouza',
    details: 'A moody landscape with emphasis on glazing and atmospheric light.',
  },
  {
    id: 'gallery-neon-muse',
    category: 'Digital',
    title: 'Neon Muse',
    artist: 'Noah James',
    image: 'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=900&q=90',
    medium: 'Digital painting',
    mentor: 'Sana Verma',
    details: 'A cinematic digital portrait exploring rim lighting and stylized color blocking.',
  },
  {
    id: 'gallery-rainbow-garden',
    category: 'Kids',
    title: 'Rainbow Garden',
    artist: 'Lila Mathew',
    image: 'https://images.unsplash.com/photo-1526948128573-703ee1aeb6fa?auto=format&fit=crop&w=900&q=90',
    medium: 'Poster color',
    mentor: 'Anita Roy',
    details: 'A playful botanical piece from our kids drawing showcase.',
  },
  {
    id: 'gallery-dream-sail',
    category: 'Anime',
    title: 'Dream Sail',
    artist: 'Ravi Menon',
    image: 'https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=90',
    medium: 'Ink and markers',
    mentor: 'Ira Nanda',
    details: 'An anime scene built around perspective, costume design, and dramatic storytelling.',
  },
];

export const workshops = [
  {
    id: 'summer-calligraphy-pen-offline',
    title: 'Summer Camp - Calligraphy with Pen',
    date: '2026-05-20T10:00:00+05:30',
    seats: 12,
    price: 1500,
    mode: 'Offline',
    image: '',
    description: 'Offline summer activity with pen calligraphy basics. Inform 2 days before starting.',
  },
  {
    id: 'summer-calligraphy-brushpen-offline',
    title: 'Summer Camp - Calligraphy with Brush Pen (Faux Calligraphy)',
    date: '2026-05-22T11:00:00+05:30',
    seats: 12,
    price: 2000,
    mode: 'Offline',
    image: '',
    description: 'Offline faux calligraphy and brush pen activity for summer learners.',
  },
  {
    id: 'summer-fabric-tote-bag',
    title: 'Summer Camp - Fabric Painting on Tote Bag',
    date: '2026-05-24T11:00:00+05:30',
    seats: 10,
    price: 900,
    mode: 'Offline',
    image: '',
    description: 'Fabric painting on tote bag with material included.',
  },
  {
    id: 'summer-fabric-toran',
    title: 'Summer Camp - Fabric Painting on Toran',
    date: '2026-05-26T11:00:00+05:30',
    seats: 10,
    price: 1000,
    mode: 'Offline',
    image: '',
    description: 'Decorative fabric painting on toran for festive home decor.',
  },
  {
    id: 'summer-canvas-painting',
    title: 'Summer Camp - Canvas Painting',
    date: '2026-05-28T11:00:00+05:30',
    seats: 10,
    price: 900,
    mode: 'Offline',
    image: '',
    description: 'Canvas painting with material included.',
  },
  {
    id: 'summer-lippan-canvas',
    title: 'Summer Camp - Lippan Art on Canvas',
    date: '2026-05-30T11:00:00+05:30',
    seats: 10,
    price: 1000,
    mode: 'Offline',
    image: '',
    description: 'Lippan art on canvas with material included.',
  },
  {
    id: 'summer-madhubani-a4',
    title: 'Summer Camp - Madhubani Painting on Handmade Paper A4',
    date: '2026-06-01T11:00:00+05:30',
    seats: 10,
    price: 600,
    mode: 'Offline',
    image: '',
    description: 'Madhubani activity on A4 handmade paper with material included.',
  },
  {
    id: 'summer-fabric-your-fabric',
    title: 'Summer Camp - Fabric Painting (Bring Your Fabric)',
    date: '2026-06-03T11:00:00+05:30',
    seats: 10,
    price: 900,
    mode: 'Offline',
    image: '',
    description: 'Fabric painting class where students bring their own fabric.',
  },
  {
    id: 'summer-arti-thali',
    title: 'Summer Camp - Arti Thali on MDF',
    date: '2026-06-05T11:00:00+05:30',
    seats: 10,
    price: 1000,
    mode: 'Offline',
    image: '',
    description: 'Arti thali making on MDF with material included.',
  },
  {
    id: 'summer-calligraphy-pen-studio-2',
    title: 'Summer Camp - Calligraphy with Pen (Evening Batch)',
    date: '2026-06-07T17:00:00+05:30',
    seats: 20,
    price: 1800,
    mode: 'Offline',
    image: '',
    description: 'Offline evening pen calligraphy summer activity for studio learners.',
  },
  {
    id: 'summer-calligraphy-brushpen-studio-2',
    title: 'Summer Camp - Calligraphy with Brush Pen (Evening Batch)',
    date: '2026-06-09T17:00:00+05:30',
    seats: 20,
    price: 2000,
    mode: 'Offline',
    image: '',
    description: 'Offline faux calligraphy and brush pen lettering summer activity.',
  },
  {
    id: 'summer-handwriting-studio',
    title: 'Summer Camp - Handwriting Improvement Classes',
    date: '2026-06-11T17:00:00+05:30',
    seats: 20,
    price: 4000,
    mode: 'Offline',
    image: '',
    description: 'Offline handwriting improvement classes for summer learners.',
  },
];

export const testimonials = [
  {
    name: 'Sofia Reed',
    role: 'Student',
    feedback: 'I grew faster in my drawing skills than I ever thought possible. The classes feel personal and inspiring.',
  },
  {
    name: 'Jasper Lin',
    role: 'Parent',
    feedback: 'The kids program is beautiful, creative, and professional. My daughter looks forward to every session.',
  },
  {
    name: 'Mira Patel',
    role: 'Artist',
    feedback: 'The workshop experience is premium and engaging. I leave with new ideas and finished pieces I am proud of.',
  },
];

export const faqs = [
  {
    question: 'Can a beginner join the academy?',
    answer: 'Yes. We offer beginner-first lessons, recorded recap support, and tailored feedback in every foundation course.',
  },
  {
    question: 'Are all classes offline?',
    answer: 'Yes. All regular classes and workshops are conducted offline at the studio.',
  },
  {
    question: 'How can I order a custom portrait?',
    answer: 'Visit the art order page, choose a style and size, upload a reference, and complete checkout to confirm your request.',
  },
  {
    question: 'How are fees tracked?',
    answer: 'Students can review fee status inside their dashboard, while admins can monitor dues, receipts, and payment milestones.',
  },
];

export const students = [
  {
    id: 'student-001',
    uid: 'demo-student-001',
    name: 'Ava Collins',
    email: 'student@example.com',
    role: 'student',
    level: 'Intermediate',
    enrolledCourses: ['Intermediate', 'Colour Pencil Shading - 4 Portraits with Basics', 'Calligraphy with Pens (Basics)'],
    workshopRegistrations: ['Summer Camp - Calligraphy with Pen', 'Summer Camp - Canvas Painting'],
    assignmentsUploaded: 24,
    certificates: 3,
    feeStatus: 'Partial',
    progressPercent: 76,
    attendanceRate: 92,
    joinedAt: '2025-11-14T10:00:00+05:30',
  },
  {
    id: 'student-002',
    uid: 'demo-student-002',
    name: 'Ravi Menon',
    email: 'ravi@example.com',
    role: 'student',
    level: 'Beginner',
    enrolledCourses: ['Elementary', 'Handwriting Improvement (English)'],
    workshopRegistrations: ['Summer Camp - Handwriting Improvement Classes'],
    assignmentsUploaded: 11,
    certificates: 1,
    feeStatus: 'Paid',
    progressPercent: 58,
    attendanceRate: 88,
    joinedAt: '2026-01-10T10:00:00+05:30',
  },
];

export const attendance = [
  { id: 'attendance-001', studentEmail: 'student@example.com', month: 'Apr 2026', attended: 11, total: 12 },
  { id: 'attendance-002', studentEmail: 'student@example.com', month: 'May 2026', attended: 10, total: 11 },
  { id: 'attendance-003', studentEmail: 'student@example.com', month: 'Jun 2026', attended: 6, total: 7 },
  { id: 'attendance-004', studentEmail: 'ravi@example.com', month: 'May 2026', attended: 7, total: 8 },
];

export const fees = [
  {
    id: 'fee-001',
    studentEmail: 'student@example.com',
    plan: 'Quarterly studio plan',
    dueDate: '2026-05-28T10:00:00+05:30',
    amount: 12500,
    paid: 8500,
    status: 'Partial',
  },
  {
    id: 'fee-002',
    studentEmail: 'student@example.com',
    plan: 'Workshop bundle',
    dueDate: '2026-06-12T10:00:00+05:30',
    amount: 3800,
    paid: 3800,
    status: 'Paid',
  },
  {
    id: 'fee-003',
    studentEmail: 'ravi@example.com',
    plan: 'Starter studio plan',
    dueDate: '2026-05-21T10:00:00+05:30',
    amount: 7200,
    paid: 7200,
    status: 'Paid',
  },
];

export const announcements = [
  {
    id: 'announcement-001',
    title: 'Portfolio review week starts Monday',
    message: 'Upload your best two pieces before Monday evening for mentor review slots.',
    audience: 'Students',
    createdAt: '2026-05-12T09:00:00+05:30',
  },
  {
    id: 'announcement-002',
    title: 'New watercolor workshop seats released',
    message: 'A final batch of weekend seats has been opened for the July watercolor intensive.',
    audience: 'Public',
    createdAt: '2026-05-10T09:00:00+05:30',
  },
];

export const progress = [
  {
    id: 'progress-001',
    studentEmail: 'student@example.com',
    category: 'Intermediate',
    completion: 72,
    milestone: 'Portfolio review',
    nextStep: 'Value contrast study',
    feedback: 'Your likeness work is strong. Push edge variety and highlights in the next portrait.',
  },
  {
    id: 'progress-002',
    studentEmail: 'student@example.com',
    category: 'Colour Pencil Shading - 4 Portraits with Basics',
    completion: 58,
    milestone: 'Wash technique practice',
    nextStep: 'Landscape layering exercise',
    feedback: 'Your color selection is elegant. Keep practicing controlled wet-on-wet transitions.',
  },
  {
    id: 'progress-003',
    studentEmail: 'student@example.com',
    category: 'Calligraphy with Pens (Basics)',
    completion: 83,
    milestone: 'Character rendering',
    nextStep: 'Final showcase piece',
    feedback: 'Your rendering depth has improved. Spend more time on composition thumbnails before painting.',
  },
  {
    id: 'progress-004',
    studentEmail: 'ravi@example.com',
    category: 'Handwriting Improvement (English)',
    completion: 61,
    milestone: 'Pose sheet review',
    nextStep: 'Turnaround character sheet',
    feedback: 'The expressions are lively. Focus on hand anatomy for the next submission.',
  },
];

export const inquiries = [
  {
    id: 'inquiry-001',
    name: 'Nina Park',
    email: 'nina.park@mail.com',
    phone: '+91 98765 43210',
    interest: 'Kids Drawing',
    message: 'I want to enroll my child in the kids drawing course for the summer batch.',
    status: 'new',
    createdAt: '2026-05-13T15:00:00+05:30',
  },
  {
    id: 'inquiry-002',
    name: 'Marco Lee',
    email: 'marco.lee@mail.com',
    phone: '+91 99887 66554',
    interest: 'Workshops',
    message: 'Do you have evening workshop slots available for working professionals?',
    status: 'contacted',
    createdAt: '2026-05-11T13:00:00+05:30',
  },
];

export const orders = [
  {
    id: 'order-001',
    studentId: 'demo-student-001',
    studentName: 'Ava Collins',
    studentEmail: 'student@example.com',
    phone: '+91 90000 11223',
    style: 'Portrait',
    size: 'A4',
    price: 6500,
    description: 'Custom portrait with soft shading and warm neutral tones.',
    referenceUrl: '',
    status: 'in-progress',
    paymentStatus: 'paid',
    deliveryStatus: 'proof shared',
    createdAt: '2026-05-08T14:00:00+05:30',
  },
  {
    id: 'order-002',
    studentId: 'demo-student-001',
    studentName: 'Ava Collins',
    studentEmail: 'student@example.com',
    phone: '+91 90000 11223',
    style: 'Sketch',
    size: 'A3',
    price: 4200,
    description: 'Charcoal family portrait commission.',
    referenceUrl: '',
    status: 'pending',
    paymentStatus: 'pending',
    deliveryStatus: 'awaiting payment',
    createdAt: '2026-05-12T11:00:00+05:30',
  },
  {
    id: 'order-003',
    studentId: 'demo-student-002',
    studentName: 'Ravi Menon',
    studentEmail: 'ravi@example.com',
    phone: '+91 90123 45678',
    style: 'Painting',
    size: 'A3',
    price: 8900,
    description: 'Landscape painting based on travel reference images.',
    referenceUrl: '',
    status: 'completed',
    paymentStatus: 'paid',
    deliveryStatus: 'delivered',
    createdAt: '2026-04-26T16:00:00+05:30',
  },
];

export const getFallbackStudent = (email, name = 'Creative Student') =>
  students.find((student) => student.email === email) || {
    id: `student-fallback-${email || 'guest'}`,
    uid: null,
    name,
    email: email || 'student@example.com',
    role: 'student',
    level: 'Beginner',
    enrolledCourses: ['Elementary', 'Calligraphy with Pens (Basics)'],
    workshopRegistrations: ['Summer Camp - Calligraphy with Pen (Evening Batch)'],
    assignmentsUploaded: 8,
    certificates: 0,
    feeStatus: 'Pending',
    progressPercent: 42,
    attendanceRate: 86,
    joinedAt: new Date().toISOString(),
  };

export const getFallbackProgress = (email) => {
  const entries = progress.filter((item) => item.studentEmail === email);
  if (entries.length > 0) return entries;

  return [
    {
      id: `progress-fallback-${email || 'guest'}`,
      studentEmail: email || 'student@example.com',
      category: 'Foundation Drawing',
      completion: 46,
      milestone: 'Shape and shading practice',
      nextStep: 'Portrait block-in exercise',
      feedback: 'You are building strong basics. Keep your sketchbook rhythm consistent this week.',
    },
  ];
};

export const getFallbackOrders = (email, name = 'Creative Student') => {
  const entries = orders.filter((item) => item.studentEmail === email);
  if (entries.length > 0) return entries;

  if (!email) return [];

  return [];
};

export const getFallbackAttendance = (email) => {
  const entries = attendance.filter((item) => item.studentEmail === email);
  if (entries.length > 0) return entries;

  return [
    { id: `attendance-fallback-${email || 'guest'}`, studentEmail: email || 'student@example.com', month: 'May 2026', attended: 7, total: 8 },
  ];
};

export const getFallbackFees = (email) => {
  const entries = fees.filter((item) => item.studentEmail === email);
  if (entries.length > 0) return entries;

  return [
    {
      id: `fee-fallback-${email || 'guest'}`,
      studentEmail: email || 'student@example.com',
      plan: 'Starter art membership',
      dueDate: new Date(Date.now() + 1000 * 60 * 60 * 24 * 10).toISOString(),
      amount: 5400,
      paid: 2700,
      status: 'Partial',
    },
  ];
};
